// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUsYxo3MYvt_ePOfrnfjo4qA0uW8aMqSY',
    appId: '1:896952882243:web:719b282ebd3c24fabf70f6',
    messagingSenderId: '896952882243',
    projectId: 'project7-f1376',
    authDomain: 'project7-f1376.firebaseapp.com',
    databaseURL: 'https://project7-f1376-default-rtdb.firebaseio.com',
    storageBucket: 'project7-f1376.appspot.com',
    measurementId: 'G-3VYSC0DW3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyk4TKh3oMT21OlrjFm4l7Z5kzNMpo6dk',
    appId: '1:896952882243:android:a507da69a23e4655bf70f6',
    messagingSenderId: '896952882243',
    projectId: 'project7-f1376',
    databaseURL: 'https://project7-f1376-default-rtdb.firebaseio.com',
    storageBucket: 'project7-f1376.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnioyZlboup1YFa5r-9ZQbNxeSwkAW_sI',
    appId: '1:896952882243:ios:681941c1cde8232fbf70f6',
    messagingSenderId: '896952882243',
    projectId: 'project7-f1376',
    databaseURL: 'https://project7-f1376-default-rtdb.firebaseio.com',
    storageBucket: 'project7-f1376.appspot.com',
    androidClientId: '896952882243-3c2b43iaqn6sam42rh53cch7vq46dsrv.apps.googleusercontent.com',
    iosClientId: '896952882243-fus8n62vnejf88unptib2k06ib2fkceq.apps.googleusercontent.com',
    iosBundleId: 'com.example.project7',
  );
}
